version: '3'

services:
  db:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  app:
    container_name: 'express-rest-ts'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
